bar {
    font pango:DejaVu Sans Mono, FontAwesome 18
    position bottom
    status_command /usr/bin/i3status-rs ~/.config/i3/config.toml
    colors {
        separator #3596ba
        background #350b68
        statusline #3596ba
        focused_workspace ##2ac984 ##2ac984 ##2ac984
        active_workspace #2ac984 #2ac984 #c9bc2a
        inactive_workspace #2da871 #2da871 #2ac984 
        urgent_workspace #d8942d #2ac984 #c9bc2a
    }
}

for_window [class="^.*"] border pixel 2
gaps inner 15
gaps outer 1

#set $netrefresh --no-startup-id sudo -A systemctl restart NetworkManager

# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 18

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 18

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec i3-sensible-terminal

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
bindsym $mod+d exec dmenu_run -fn 'Overpass Mono:pixelsize=18' -l 3 -nf '#707880' -sf '#cc6666' -nb '#1d1f21' -sb '#1d1f21'

# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right
focus_follows_mouse no
# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child



# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $workspace3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $workspace3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10


# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $workspace3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

assign [class="Vivaldi-stable"] $ws1
assign [class="URxvt"] $ws2
for_window [class="Spotify"] move to workspace $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec exit

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if avail




exec_always feh --bg-scale ~/Pictures/wallpaper.jpg

# Set display mode
#exec_always xrandr --output Virtual1 --mode 1360x768

exec_always compton -f
 exec_always --no-startup-id feh --bg-scale ~/.wallpaper.jpg

 exec /usr/bin/spotify

 exec /usr/bin/urxvt		

exec /usr/bin/vivaldi-stable

new_window pixel 2

hide_edge_borders vertical

# Color variables
set $unfocused_border #2a1349
set $focused_border #6b7a19

# class                 border  backgr. text    indicator child_border
client.focused          #6b7a19  #6b7a19 #6b7a19 #6b7a19   $focused_border
client.focused_inactive #2a1349 #2a1349 #2a1349 #2a1349  $focused_border
client.unfocused        #2a1349 #2a1349 #2a1349 #2a1349   $unfocused_border
client.urgent           #2a1349 #2a1349 #2a1349 #2a1349   $focused_border
client.placeholder      #2a1349 #2a1349 #2a1349 #2a1349   #2a1349

client.background       #2a1349

# Apply .Xresource. As far as I know, only needed here if using starx (dont have a login manager)
exec_always --no-startup-id xrdb ~/.Xresources


# Pulse Audio controls
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume 0 +5% #increase sound volume
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume 0 -5% #decrease sound volume
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute 0 toggle # mute sound

# Media player controls
#bindsym XF86AudioPlay exec playerctl play
#bindsym XF86AudioPause exec playerctl pause
#bindsym XF86AudioNext exec playerctl next
#bindsym XF86AudioPrev exec playerctl previous

#bindsym XF86PowerOff		exec --no-startup-id prompt "Shutdown computer?" "$shutdown"
bindsym XF86Copy		exec
##bindsym XF86Open		exec
bindsym XF86Paste		exec
bindsym XF86Cut		exec
##bindsym XF86MenuKB		exec
#bindsym XF86Calculator		exec --no-startup-id ddspawn dropdowncalc -f mono:pixelsize=24
##bindsym XF86Sleep		This binding is typically mapped by systemd automatically.
##bindsym XF86WakeUp		exec
#bindsym XF86Explorer		exec $term -e $FILE
##bindsym XF86Send		exec
##bindsym XF86Xfer		exec
#bindsym XF86WWW			exec --no-startup-id $BROWSER
##bindsym XF86DOS		exec
#bindsym XF86ScreenSaver		exec exec --no-startup-id lockscreen
##bindsym XF86RotateWindows	exec
##bindsym XF86TaskPane		exec
##bindsym XF86Favorites		exec
#bindsym XF86MyComputer		exec $term -e $FILE
##bindsym XF86Back		exec
##bindsym XF86Forward		exec
#bindsym XF86Eject		exec --no-startup-id dmenuumount
#bindsym XF86AudioNext		exec --no-startup-id lmc next
#bindsym XF86AudioPlay		exec --no-startup-id lmc toggle
#bindsym XF86AudioPrev		exec --no-startup-id lmc prev
#bindsym XF86AudioStop		exec --no-startup-id lmc toggle
##bindsym XF86AudioRecord
#bindsym XF86AudioRewind		exec --no-startup-id lmc back 10
#bindsym XF86AudioForward	exec --no-startup-id lmc forward 10
##bindsym XF86Phone		exec
##bindsym XF86Tools		exec
#bindsym XF86HomePage		exec $BROWSER https://lukesmith.xyz
#bindsym XF86Reload		restart
##bindsym XF86ScrollUp		exec
##bindsym XF86ScrollDown		exec
##bindsym XF86New		exec
##bindsym XF86LaunchA		exec
##bindsym XF86LaunchB		exec
##bindsym XF86Launch2		exec
##bindsym XF86Launch3		exec
##bindsym XF86Launch4		exec
##bindsym XF86Launch5		exec
##bindsym XF86Launch6		exec
##bindsym XF86Launch7		exec
##bindsym XF86Launch8		exec
##bindsym XF86Launch9		exec
#bindsym XF86AudioMicMute	exec $micmute
#bindsym XF86TouchpadToggle	exec --no-startup-id toggletouchpad
#bindsym XF86TouchpadOn		exec --no-startup-id synclient TouchpadOff=0
#bindsym XF86TouchpadOff		exec --no-startup-id synclient TouchpadOff=1
#bindsym XF86Suspend		exec --no-startup-id lockscreen
#bindsym XF86Close		kill
#bindsym XF86WebCam		exec --no-startup-id camtoggle
#bindsym XF86Mail		exec $term -e neomutt && pkill -RTMIN+12 i3blocks
#bindsym XF86Messenger		exec $term -e weechat
#bindsym XF86Search		exec $BROWSER https://duckduckgo.com
##bindsym XF86Go			exec
##bindsym XF86Finance		exec
##bindsym XF86Game		exec
#bindsym XF86Shop		exec $BROWSER https://ebay.com
#bindsym XF86MonBrightnessDown	exec --no-startup-id xbacklight -dec 15
#bindsym XF86MonBrightnessUp	exec --no-startup-id xbacklight -inc 15
#bindsym XF86AudioMedia		exec --no-startup-id $term -e ncmpcpp
#bindsym XF86Display		exec --no-startup-id displayselect
#bindsym XF86KbdLightOnOff	exec
#bindsym XF86KbdBrightnessDown	exec
#bindsym XF86KbdBrightnessUp	exec
##bindsym XF86Reply		exec
##bindsym XF86MailForward	exec
##bindsym XF86Save		exec
#bindsym XF86Documents		exec $term -e $FILE ~/Documents
##bindsym XF86Battery		exec
##bindsym XF86Bluetooth		exec
#bindsym XF86WLAN		exec $netrefresh
